### ISSUE TITLE
Goal reset? 

### ISSUE THREAD

**Issue by jmbruel** [CodyJung/connectiq-apps#5] opened 2015-07-21 06:15 UTC
Each time I set a new goal the entered number just adds to the previous number! Can't find how to reset the goal.

**Comment by CodyJung** [comment] 2015-08-06 18:41
Ach, sorry - I apparently don't get emails for new issues.
I'm not seeing that happen on my watch. What version of Fenix 3 (or D2 Bravo) software do you have?

**Comment by CodyJung** [comment] 2015-09-07 21:56
I'm going to close this as Can't Reproduce. Also try taking a look at version 1.1.0 - I changed how the number picker works, and hopefully that'll fix your issue?

**Closed as completed by CodyJung** 2015-09-07 21:56 UTC
